In [0]:
!pip3 install pandas plotly numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (1.0.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (4.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (1.18.4)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from plotly) (1.12.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly) (1.3.3)

In [0]:
import pandas as pd
import numpy as np

In [0]:
base_url='https://gist.githubusercontent.com/alti-tude/710cb9d4dfc7ebcd0afb9cf93d8f6a8d/raw/574730ba009e69b81d6c79f2fef2c3dd5145db0a/'

In [0]:
#load data
music=pd.read_csv(base_url+'MusicTop50.csv', index_col=0)

                        Track.Name    Artist.Name  ... Speechiness  Popularity
1                         Se�orita   Shawn Mendes  ...           3        79.0
2                            China       Anuel AA  ...           9        92.0
3    boyfriend (with Social House)  Ariana Grande  ...          46        85.0
4  Beautiful People (feat. Khalid)     Ed Sheeran  ...          19        86.0
5      Goodbyes (Feat. Young Thug)    Post Malone  ...           7        94.0

[5 rows x 13 columns]

In [0]:
#visualize
music.head()

                        track_name    artist_name  ... speechiness  popularity
1                         Se�orita   Shawn Mendes  ...           3        79.0
2                            China       Anuel AA  ...           9        92.0
3    boyfriend (with Social House)  Ariana Grande  ...          46        85.0
4  Beautiful People (feat. Khalid)     Ed Sheeran  ...          19        86.0
5      Goodbyes (Feat. Young Thug)    Post Malone  ...           7        94.0

[5 rows x 13 columns]

In [0]:
music.tail()

                                       track_name  ... popularity
46                                One Thing Right  ...       88.0
47                                      Te Robar�  ...       88.0
48                                        Happier  ...       88.0
49                                  Call You Mine  ...       88.0
50  Cross Me (feat. Chance the Rapper & PnB Rock)  ...       82.0

[5 rows x 13 columns]

In [0]:
# clean data
#make column names proper
music.columns=['track_name','artist_name','genre','beats_per_minute','energy','danceability(db)','loudness','liveness','valence()','length','acousticness','speechiness','popularity']
music.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 1 to 50
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_name        50 non-null     object
 1   artist_name       50 non-null     object
 2   genre             50 non-null     object
 3   beats_per_minute  48 non-null     float64
 4   energy            49 non-null     float64
 5   danceability(db)  50 non-null     int64
 6   loudness          50 non-null     int64
 7   liveness          48 non-null     float64
 8   valence()         49 non-null     float64
 9   length            47 non-null     float64
 10  acousticness      50 non-null     int64
 11  speechiness       50 non-null     int64
 12  popularity        49 non-null     float64
dtypes: float64(6), int64(4), object(3)
memory usage: 5.5+ KB

In [0]:
#handle null values
#by dropping rows
music.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41 entries, 1 to 50
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_name        41 non-null     object
 1   artist_name       41 non-null     object
 2   genre             41 non-null     object
 3   beats_per_minute  41 non-null     float64
 4   energy            41 non-null     float64
 5   danceability(db)  41 non-null     int64
 6   loudness          41 non-null     int64
 7   liveness          41 non-null     float64
 8   valence()         41 non-null     float64
 9   length            41 non-null     float64
 10  acousticness      41 non-null     int64
 11  speechiness       41 non-null     int64
 12  popularity        41 non-null     float64
dtypes: float64(6), int64(4), object(3)
memory usage: 4.5+ KB

In [0]:
#by replacing it with mean
music_mean=music.mean()
music.fillna(music_mean).head()

                        track_name    artist_name  ... speechiness  popularity
1                         Se�orita   Shawn Mendes  ...           3        79.0
2                            China       Anuel AA  ...           9        92.0
3    boyfriend (with Social House)  Ariana Grande  ...          46        85.0
4  Beautiful People (feat. Khalid)     Ed Sheeran  ...          19        86.0
5      Goodbyes (Feat. Young Thug)    Post Malone  ...           7        94.0

[5 rows x 13 columns]

In [0]:
#by replacing it with median
music_median=music.median()
music.fillna(music_median).head()

                        track_name    artist_name  ... speechiness  popularity
1                         Se�orita   Shawn Mendes  ...           3        79.0
2                            China       Anuel AA  ...           9        92.0
3    boyfriend (with Social House)  Ariana Grande  ...          46        85.0
4  Beautiful People (feat. Khalid)     Ed Sheeran  ...          19        86.0
5      Goodbyes (Feat. Young Thug)    Post Malone  ...           7        94.0

[5 rows x 13 columns]

In [0]:
music[music['artist_name']==music.sort_values(by=['popularity']).iloc[0]['artist_name']].sort_values(by=['loudness'],ascending=False).iloc[0]['track_name']

"If I Can't Have You"

In [0]:
import plotly.graph_objects as go